server:
  port: 8181
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:4433/gogodb
    username: postgres
    password: postgres
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    drop-first: false
    default-schema: public
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
